version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=0
      - DATABASE_URI=mysql://root:root@db/miproyecto
    links:
      - db
    depends_on:
     - db

  db_mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'miproyecto'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db_mysql:/var/lib/mysql

  db_postgres:
    image: postgres:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'miproyecto'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - my-db_postgres:/var/lib/postgresql
volumes:
  my-db_mysql:
  my-db_postgres: