version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=0
      - DATABASE_URI=mysql://root:root@db/miproyecto
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'miproyecto'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_ROOT_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - my-db:/var/lib/postgresql
volumes:
  my-db: